export type CardClass =
  | 'MAGE'
  | 'DRUID'
  | 'HUNTER'
  | 'PRIEST'
  | 'WARLOCK'
  | 'SHAMAN'
  | 'WARRIOR'
  | 'ROGUE'
  | 'PALADIN'
  | 'NEUTRAL';

export interface HSReplayMap {
  dbfId: number;
  cardClass: CardClass;
  name: string;
  cardCode: string;
}

export const hsreplayMap: ReadonlyArray<HSReplayMap> = [
  {
    dbfId: 46499,
    cardClass: 'MAGE',
    name: '용소환사 알라나',
    cardCode: 'Drgoncaller_Alanna',
  },
  {
    dbfId: 43426,
    cardClass: 'MAGE',
    name: '알루네스',
    cardCode: 'Aluneth',
  },
  {
    dbfId: 45271,
    cardClass: 'MAGE',
    name: '용의 분노',
    cardCode: "Dragon's Fury",
  },
  {
    dbfId: 43424,
    cardClass: 'MAGE',
    name: '신비의 덱',
    cardCode: 'Deck_of_Wonders',
  },
  {
    dbfId: 46541,
    cardClass: 'MAGE',
    name: '지맥 조작꾼',
    cardCode: 'Leyline_Manupulator',
  },
  {
    dbfId: 43414,
    cardClass: 'MAGE',
    name: '하급 루비 주문석',
    cardCode: 'Lesser_Ruby_Spellstone',
  },
  {
    dbfId: 43407,
    cardClass: 'MAGE',
    name: '폭발의 룬',
    cardCode: 'Explosive_Runes',
  },
  {
    dbfId: 45590,
    cardClass: 'MAGE',
    name: '비전 기술병',
    cardCode: 'Arcane_Artificer',
  },
  {
    dbfId: 45269,
    cardClass: 'MAGE',
    name: '까마귀 전령',
    cardCode: 'Raven_Familiar',
  },
  {
    dbfId: 43420,
    cardClass: 'MAGE',
    name: '변화하는 두루마리',
    cardCode: 'Shifting_Scroll',
  },
  {
    dbfId: 46390,
    cardClass: 'HUNTER',
    name: '카트레나 윈터위습',
    cardCode: 'Kathrena_Winterwisp',
  },
  {
    dbfId: 43369,
    cardClass: 'HUNTER',
    name: '라크델라',
    cardCode: "Rhok'delar",
  },
  {
    dbfId: 46450,
    cardClass: 'HUNTER',
    name: '다가오는 벽',
    cardCode: 'Crushing_Walls',
  },
  {
    dbfId: 45546,
    cardClass: 'HUNTER',
    name: '이리 와라!',
    cardCode: 'To_My_Side',
  },
  {
    dbfId: 43363,
    cardClass: 'HUNTER',
    name: '하급 에메랄드 주문석',
    cardCode: 'Lesser_Emerald_Spellstone',
  },
  {
    dbfId: 46445,
    cardClass: 'HUNTER',
    name: '스며나오는 수액덩어리',
    cardCode: 'Seeping_Oozeling',
  },
  {
    dbfId: 43359,
    cardClass: 'HUNTER',
    name: '떠도는 괴물',
    cardCode: 'Wandering_Monster',
  },
  {
    dbfId: 43358,
    cardClass: 'HUNTER',
    name: '동굴 히드라',
    cardCode: 'Cave_Hydra',
  },
  {
    dbfId: 43357,
    cardClass: 'HUNTER',
    name: '측방 강타',
    cardCode: 'Flanking_Strike',
  },
  {
    dbfId: 45537,
    cardClass: 'HUNTER',
    name: '양초 화살',
    cardCode: 'Candleshot',
  },
  {
    dbfId: 45263,
    cardClass: 'ROGUE',
    name: '소냐 섀도댄서',
    cardCode: 'Sonya_Shadowdancer',
  },
  {
    dbfId: 47035,
    cardClass: 'ROGUE',
    name: '왕의 파멸',
    cardCode: 'Kingsbane',
  },
  {
    dbfId: 45535,
    cardClass: 'ROGUE',
    name: '회피',
    cardCode: 'Evasion',
  },
  {
    dbfId: 43228,
    cardClass: 'ROGUE',
    name: '팔도레이 순찰자',
    cardCode: "Fal'dorei Strider",
  },
  {
    dbfId: 45531,
    cardClass: 'ROGUE',
    name: '엘프 음악가',
    cardCode: 'Elven_Minstrel',
  },
  {
    dbfId: 46296,
    cardClass: 'ROGUE',
    name: '하급 흑마노 주문석',
    cardCode: 'Lesser_Onyx_Spellstone',
  },
  {
    dbfId: 45936,
    cardClass: 'ROGUE',
    name: '코볼트 환영술사',
    cardCode: 'Kobold_Illusionist',
  },
  {
    dbfId: 43237,
    cardClass: 'ROGUE',
    name: '동굴 금속탐지꾼',
    cardCode: 'Cavern_Shinyfinder',
  },
  {
    dbfId: 45520,
    cardClass: 'ROGUE',
    name: '구사일생',
    cardCode: 'Cheat_Death',
  },
  {
    dbfId: 45529,
    cardClass: 'ROGUE',
    name: '갑작스러운 배신',
    cardCode: 'Sudden_Betrayal',
  },
  {
    dbfId: 46442,
    cardClass: 'WARRIOR',
    name: '대지조각가 이프',
    cardCode: 'Geosulptor_Yip',
  },
  {
    dbfId: 46077,
    cardClass: 'WARRIOR',
    name: '비통의 가로날도끼',
    cardCode: 'Woecleaver',
  },
  {
    dbfId: 46026,
    cardClass: 'WARRIOR',
    name: '무모한 난동',
    cardCode: 'Reckless_Flurry',
  },
  {
    dbfId: 43277,
    cardClass: 'WARRIOR',
    name: '칼날주먹',
    cardCode: 'Bladed_Gauntlet',
  },
  {
    dbfId: 45519,
    cardClass: 'WARRIOR',
    name: '하급 미스릴 주문석',
    cardCode: 'Lesser_Mithrill_Spellstone',
  },
  {
    dbfId: 46058,
    cardClass: 'WARRIOR',
    name: '파티 모집',
    cardCode: 'Gather_Your_Party',
  },
  {
    dbfId: 43269,
    cardClass: 'WARRIOR',
    name: '코볼트 야만용사',
    cardCode: 'Kobold_Barbarian',
  },
  {
    dbfId: 46031,
    cardClass: 'WARRIOR',
    name: '마른수염 방어구 제작자',
    cardCode: 'Drywhisker_Armorer',
  },
  {
    dbfId: 45775,
    cardClass: 'WARRIOR',
    name: '정체불명의 방패',
    cardCode: 'Unidentified_Shield',
  },
  {
    dbfId: 46027,
    cardClass: 'WARRIOR',
    name: '보석 박힌 골렘',
    cardCode: 'Gemstudded_Golem',
  },
  {
    dbfId: 46040,
    cardClass: 'WARLOCK',
    name: '첫 번째 사도 린',
    cardCode: 'Rin_the_First_Disciple',
  },
  {
    dbfId: 46299,
    cardClass: 'WARLOCK',
    name: '만아리의 해골',
    cardCode: "Skull_of_the_Man'ari",
  },
  {
    dbfId: 46056,
    cardClass: 'WARLOCK',
    name: '공허군주',
    cardCode: 'Voidlord',
  },
  {
    dbfId: 46286,
    cardClass: 'WARLOCK',
    name: '대격변',
    cardCode: 'Cataclysm',
  },
  {
    dbfId: 45820,
    cardClass: 'WARLOCK',
    name: '지배당한 졸개',
    cardCode: 'Possessed_Lackey',
  },
  {
    dbfId: 43133,
    cardClass: 'WARLOCK',
    name: '갈고리 약탈자',
    cardCode: 'Hooked_Reaver',
  },
  {
    dbfId: 43272,
    cardClass: 'WARLOCK',
    name: '하급 자수정 주문석',
    cardCode: 'Lesser_Amethyst_Spellstone',
  },
  {
    dbfId: 43128,
    cardClass: 'WARLOCK',
    name: '어둠의 서약',
    cardCode: 'Dark_Pact',
  },
  {
    dbfId: 43121,
    cardClass: 'WARLOCK',
    name: '야비한 소악마',
    cardCode: 'Vulgar_Homunculus',
  },
  {
    dbfId: 43122,
    cardClass: 'WARLOCK',
    name: '코볼트 사서',
    cardCode: 'Kobold_Librarian',
  },
  {
    dbfId: 46305,
    cardClass: 'SHAMAN',
    name: '룬의 창',
    cardCode: 'The_Runespear',
  },
  {
    dbfId: 45995,
    cardClass: 'SHAMAN',
    name: '세계전율자 그럼블',
    cardCode: 'Grumble_Worldshaker',
  },
  {
    dbfId: 46440,
    cardClass: 'SHAMAN',
    name: '칼바람 폭풍소환사',
    cardCode: 'Windshear_Stormcaller',
  },
  {
    dbfId: 46303,
    cardClass: 'SHAMAN',
    name: '불안정한 진화',
    cardCode: 'Unstable_Evolution',
  },
  {
    dbfId: 46432,
    cardClass: 'SHAMAN',
    name: '메아리치는 정령',
    cardCode: 'Murmuring_Elemental',
  },
  {
    dbfId: 43331,
    cardClass: 'SHAMAN',
    name: '하급 사파이어 주문석',
    cardCode: 'Lesser_Sapphire_Spellstone',
  },
  {
    dbfId: 45905,
    cardClass: 'SHAMAN',
    name: '원시의 부적',
    cardCode: 'Primal_Talismans',
  },
  {
    dbfId: 46067,
    cardClass: 'SHAMAN',
    name: '치유의 비',
    cardCode: 'Healing_Rain',
  },
  {
    dbfId: 43322,
    cardClass: 'SHAMAN',
    name: '분쇄의 손',
    cardCode: 'Crushing_Hand',
  },
  {
    dbfId: 43329,
    cardClass: 'SHAMAN',
    name: '코볼트 은둔자',
    cardCode: 'Kobold_Hermit',
  },
  {
    dbfId: 46544,
    cardClass: 'PRIEST',
    name: '템퍼루스',
    cardCode: 'Temporus',
  },
  {
    dbfId: 45528,
    cardClass: 'PRIEST',
    name: '용의 영혼',
    cardCode: 'Dragon_Soul',
  },
  {
    dbfId: 43112,
    cardClass: 'PRIEST',
    name: '영혼의 절규',
    cardCode: 'Psychic_Scream',
  },
  {
    dbfId: 46460,
    cardClass: 'PRIEST',
    name: '황혼의 수행사제',
    cardCode: 'Twilight_Acolyte',
  },
  {
    dbfId: 46307,
    cardClass: 'PRIEST',
    name: '하급 다이아몬드 주문석',
    cardCode: 'Lesser_Diamond_Spellstone',
  },
  {
    dbfId: 45353,
    cardClass: 'PRIEST',
    name: '황혼의 부름',
    cardCode: "Twilight's_Call",
  },
  {
    dbfId: 45899,
    cardClass: 'PRIEST',
    name: '황혼파괴자',
    cardCode: 'Duskbreaker',
  },
  {
    dbfId: 46495,
    cardClass: 'PRIEST',
    name: '금박 가고일',
    cardCode: 'Giled_Gargoyle',
  },
  {
    dbfId: 45759,
    cardClass: 'PRIEST',
    name: '정체불명의 비약',
    cardCode: 'Unidentified_Elixir',
  },
  {
    dbfId: 45979,
    cardClass: 'PRIEST',
    name: '정신 관찰',
    cardCode: 'Psonic_Probe',
  },
  {
    dbfId: 45539,
    cardClass: 'PALADIN',
    name: '리네사 선소로우',
    cardCode: 'Lynessa_Sunsorrow',
  },
  {
    dbfId: 46263,
    cardClass: 'PALADIN',
    name: '발아니르',
    cardCode: "Val'anyr",
  },
  {
    dbfId: 43384,
    cardClass: 'PALADIN',
    name: '긴급 소집',
    cardCode: 'Call_to_Arms',
  },
  {
    dbfId: 45877,
    cardClass: 'PALADIN',
    name: '레벨 업!',
    cardCode: 'Level_Up',
  },
  {
    dbfId: 45833,
    cardClass: 'PALADIN',
    name: '수정 사자',
    cardCode: 'Crystal_Lion',
  },
  {
    dbfId: 43382,
    cardClass: 'PALADIN',
    name: '하급 진주 주문석',
    cardCode: 'Lesser_Pearl_Spellstone',
  },
  {
    dbfId: 45782,
    cardClass: 'PALADIN',
    name: '정체불명의 망치',
    cardCode: 'Unidentified_Maul',
  },
  {
    dbfId: 43373,
    cardClass: 'PALADIN',
    name: '무용의 물약',
    cardCode: 'Potion_of_Heroism',
  },
  {
    dbfId: 46258,
    cardClass: 'PALADIN',
    name: '자애로운 신령',
    cardCode: 'Benevolent_Djinn',
  },
  {
    dbfId: 46007,
    cardClass: 'PALADIN',
    name: '마른협곡 교도관',
    cardCode: 'Drygulch_Jailor',
  },
  {
    dbfId: 45859,
    cardClass: 'DRUID',
    name: '곰팡이 군주 익슬리드',
    cardCode: 'Ixlid_Fungal_Lord',
  },
  {
    dbfId: 46107,
    cardClass: 'DRUID',
    name: '세계수의 가지',
    cardCode: 'Twig_of_the_World_Tree',
  },
  {
    dbfId: 43294,
    cardClass: 'DRUID',
    name: '갈림길',
    cardCode: 'Branching_Paths',
  },
  {
    dbfId: 43304,
    cardClass: 'DRUID',
    name: '천공의 호랑이',
    cardCode: 'Astral_Tiger',
  },
  {
    dbfId: 45835,
    cardClass: 'DRUID',
    name: '불곰 수호병',
    cardCode: 'Grizzled_Guardian',
  },
  {
    dbfId: 45945,
    cardClass: 'DRUID',
    name: '욕심쟁이 요마',
    cardCode: 'Greedy_Sprite',
  },
  {
    dbfId: 43288,
    cardClass: 'DRUID',
    name: '하급 벽옥 주문석',
    cardCode: 'Lesser_Jesper_Spellstone',
  },
  {
    dbfId: 43284,
    cardClass: 'DRUID',
    name: '강철나무 골렘',
    cardCode: 'Ironwood_Golem',
  },
  {
    dbfId: 45828,
    cardClass: 'DRUID',
    name: '참나무 소환술',
    cardCode: 'Oaken_Summons',
  },
  {
    dbfId: 43282,
    cardClass: 'DRUID',
    name: '나무 껍질',
    cardCode: 'Barkskin',
  },
  {
    dbfId: 45988,
    cardClass: 'NEUTRAL',
    name: '교활한 마린',
    cardCode: 'Marin_the_Fox',
  },
  {
    dbfId: 46449,
    cardClass: 'NEUTRAL',
    name: '달인 오크하트',
    cardCode: 'Master_Oakheart',
  },
  {
    dbfId: 46589,
    cardClass: 'NEUTRAL',
    name: '미궁왕 토그왜글',
    cardCode: 'King_Togwaggle',
  },
  {
    dbfId: 46454,
    cardClass: 'NEUTRAL',
    name: '어둠의 존재',
    cardCode: 'The_Darkness',
  },
  {
    dbfId: 46403,
    cardClass: 'NEUTRAL',
    name: '고르곤 졸라',
    cardCode: 'Zola_the_Gorgon',
  },
  {
    dbfId: 46557,
    cardClass: 'NEUTRAL',
    name: '용 사육사',
    cardCode: 'Dragonhatcher',
  },
  {
    dbfId: 46892,
    cardClass: 'NEUTRAL',
    name: '희미하게 빛나는 군마',
    cardCode: 'Shimmering_Courser',
  },
  {
    dbfId: 43515,
    cardClass: 'NEUTRAL',
    name: '징그러운 지하 벌레',
    cardCode: 'Corridor_Creeper',
  },
  {
    dbfId: 46032,
    cardClass: 'NEUTRAL',
    name: '고위 기록관',
    cardCode: 'Grand_Archivist',
  },
  {
    dbfId: 43483,
    cardClass: 'NEUTRAL',
    name: '비전 폭군',
    cardCode: 'Arcane_Tyrant',
  },
  {
    dbfId: 46551,
    cardClass: 'NEUTRAL',
    name: '원한 맺힌 소환사',
    cardCode: 'Spiteful_Summoner',
  },
  {
    dbfId: 45195,
    cardClass: 'NEUTRAL',
    name: '육식 보물상자',
    cardCode: 'Carnivorous_Cube',
  },
  {
    dbfId: 46461,
    cardClass: 'NEUTRAL',
    name: '공허 학살자',
    cardCode: 'Void_Ripper',
  },
  {
    dbfId: 46088,
    cardClass: 'NEUTRAL',
    name: '뒤적거리는 코볼트',
    cardCode: 'Rummaging_Kobold',
  },
  {
    dbfId: 46118,
    cardClass: 'NEUTRAL',
    name: '비명쟁이 버섯',
    cardCode: 'Shrieking_Shroom',
  },
  {
    dbfId: 46079,
    cardClass: 'NEUTRAL',
    name: '코볼트 수도사',
    cardCode: 'Kobold_Monk',
  },
  {
    dbfId: 43528,
    cardClass: 'NEUTRAL',
    name: '자갈주둥이 기사',
    cardCode: 'Gravelsnout_Knight',
  },
  {
    dbfId: 43465,
    cardClass: 'NEUTRAL',
    name: '칠흑의 용 대장장이',
    cardCode: 'Ebon_Dragonsmith',
  },
  {
    dbfId: 46082,
    cardClass: 'NEUTRAL',
    name: '굶주린 거인',
    cardCode: 'Hungry_Ettin',
  },
  {
    dbfId: 43517,
    cardClass: 'NEUTRAL',
    name: '펄볼그 이끼결속사',
    cardCode: 'Furbolg_Mossbinder',
  },
  {
    dbfId: 43473,
    cardClass: 'NEUTRAL',
    name: '고독한 용사',
    cardCode: 'Lone_Champion',
  },
  {
    dbfId: 45547,
    cardClass: 'NEUTRAL',
    name: '떠버리 야수',
    cardCode: 'Feral_Gibberer',
  },
  {
    dbfId: 43453,
    cardClass: 'NEUTRAL',
    name: '전갈로봇',
    cardCode: 'Scorp_o_matic',
  },
  {
    dbfId: 43463,
    cardClass: 'NEUTRAL',
    name: '밀랍 정령',
    cardCode: 'Wax_elemental',
  },
  {
    dbfId: 45930,
    cardClass: 'NEUTRAL',
    name: '단단한 딱정벌레',
    cardCode: 'Plated_Beetle',
  },
  {
    dbfId: 43526,
    cardClass: 'NEUTRAL',
    name: '보랏빛 땅벌레',
    cardCode: 'Violet_Wurm',
  },
  {
    dbfId: 45837,
    cardClass: 'NEUTRAL',
    name: '트로그 버섯먹보',
    cardCode: 'Trogg_Gloomeater',
  },
  {
    dbfId: 43489,
    cardClass: 'NEUTRAL',
    name: '덥석 상자',
    cardCode: 'Toothy_Chest',
  },
  {
    dbfId: 43474,
    cardClass: 'NEUTRAL',
    name: '돌가죽 바실리스크',
    cardCode: 'Stoneskin_Basilisk',
  },
  {
    dbfId: 43493,
    cardClass: 'NEUTRAL',
    name: '약삭빠른 악마',
    cardCode: 'Sneaky_Devil',
  },
  {
    dbfId: 45784,
    cardClass: 'NEUTRAL',
    name: '버섯 물약꾼',
    cardCode: 'Shroom_Brewer',
  },
  {
    dbfId: 43345,
    cardClass: 'NEUTRAL',
    name: '시궁창 엉금이',
    cardCode: 'Sewer_Crawler',
  },
  {
    dbfId: 45929,
    cardClass: 'NEUTRAL',
    name: '코볼트 수습생',
    cardCode: 'Kobold_Apprentice',
  },
  {
    dbfId: 43485,
    cardClass: 'NEUTRAL',
    name: '녹색 점액괴물',
    cardCode: 'Green_Jelly',
  },
  {
    dbfId: 45265,
    cardClass: 'NEUTRAL',
    name: '곰팡이술사',
    cardCode: 'Fungalmancer',
  },
  {
    dbfId: 46087,
    cardClass: 'NEUTRAL',
    name: '버섯 마법부여사',
    cardCode: 'Fungal_Enchanter',
  },
  {
    dbfId: 43486,
    cardClass: 'NEUTRAL',
    name: '용사냥꾼',
    cardCode: 'Dragonslayer',
  },
  {
    dbfId: 45707,
    cardClass: 'NEUTRAL',
    name: '사나운 두더지',
    cardCode: 'Dire_Mole',
  },
  {
    dbfId: 45594,
    cardClass: 'NEUTRAL',
    name: '저주받은 사도',
    cardCode: 'Cursed_Disciple',
  },
  {
    dbfId: 43469,
    cardClass: 'NEUTRAL',
    name: '부식성 녹괴물',
    cardCode: 'Corrosive_Sludge',
  },
  {
    dbfId: 43523,
    cardClass: 'NEUTRAL',
    name: '활기찬 음유시인',
    cardCode: 'Boisterous_Bard',
  },
  {
    dbfId: 43494,
    cardClass: 'NEUTRAL',
    name: '잠꾸러기 용',
    cardCode: 'Sleepy_Dragon',
  },
  {
    dbfId: 46069,
    cardClass: 'NEUTRAL',
    name: '길드 소집관',
    cardCode: 'Guild_Recruiter',
  },
  {
    dbfId: 45287,
    cardClass: 'NEUTRAL',
    name: '은빛 선봉대원',
    cardCode: 'Silver_Vanguard',
  },
  {
    dbfId: 43507,
    cardClass: 'NEUTRAL',
    name: '보물을 지키는 용',
    cardCode: 'Hoarding_Dragon',
  },
];
